name = "StarBattle"
uuid = "048000c3-e79e-41fc-9d43-8c3cde733e38"
authors = ["ngngardner <ngngardner@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
SimpleGraphAlgorithms = "41400c72-0c58-5c16-8579-4ecbce768449"
SimpleGraphs = "55797a34-41de-5266-9ec1-32ac4eb504d3"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
